### ISSUE TITLE
Break in IE11

### ISSUE THREAD

**Issue by eldyvoon** [LvChengbin/url#2]
I was search polyfil for IE11's URLSearchParams, tried it and it break.

**Comment by LvChengbin** [comment]
@eldyvoon Would you like to provide some details such as your code and error messages.

**Comment by eldyvoon** [comment]
it's not my code it's your code

**Comment by eldyvoon** [comment]
@LvChengbin it worked for you? I removed my code already, it's hard for me to reproduce.

**Comment by LvChengbin** [comment]
@eldyvoon Yes, it works. But I am so sorry for the bugs you encountered.
